In [2]:
import numpy as np
import torch

In [3]:
a = np.array([2,3.3])
torch.from_numpy(a)

tensor([2.0000, 3.3000], dtype=torch.float64)

In [4]:
a = np.ones([2,3])
torch.from_numpy(a)

tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [5]:
# tensor 小写：接收现有数据 大写：接受shape（少用）

In [ ]:
# uninitialized
Torch.FloatTensor(d1,d2,d3)

In [6]:
torch.empty(1)

tensor([0.])

In [7]:
torch.Tensor(2,3)

tensor([[0.0000e+00, 4.6566e-10, 0.0000e+00],
        [4.6566e-10, 2.4158e-12, 1.1625e+33]])

In [ ]:
# 增强学习一般使用 doubleTensor