In [ ]:
# python       |              PyTorch
#  int         |          IntTensor of size() 
#  float       |          FloatTensor of size()
# int array    |          IntTensor of size [d1,d2,...]
# Float array  |         FloatTensor of size [d1,d2,...]
#  string      |               ------------

# How to demote string
# 1. One-hot encode
# 2. Embedding   Word2vec|glove

In [6]:
import torch
a = torch.randn(2,3) # 随机初始化 两行三列
a.type()

'torch.FloatTensor'

In [7]:
type(a)

torch.Tensor

In [8]:
isinstance(a, torch.FloatTensor)

True

In [9]:
# 严格来说，称仅包含一个数值的叫标量( dimension 为 0) （loss）
torch.tensor(1.)

tensor(1.)

In [10]:
torch.tensor(1.3)

tensor(1.3000)

In [11]:
b = torch.tensor(2.2)
b.shape

torch.Size([])

In [12]:
len(b.shape)

0

In [15]:
b.size()

torch.Size([])

In [16]:
# dimension = 1的tensor  （bias）
torch.tensor([1.1])

tensor([1.1000])

In [19]:
torch.FloatTensor(2) # 数据是random初始化的

tensor([ 0.0000e+00, -3.6893e+19])

In [21]:
# size shape
# dimension为2 -》 linear input batch
c = torch.randn(2,3)
c

tensor([[ 0.9299,  0.3833, -0.7021],
        [ 0.6280,  0.0243,  1.6110]])

In [22]:
c.shape

torch.Size([2, 3])

In [23]:
c.size(0)

2

In [24]:
c.size(1)

3

In [27]:
# dimension为3  (RNN)
d = torch.rand(2,2,3)
d

tensor([[[0.0600, 0.9531, 0.0988],
         [0.6665, 0.7784, 0.6273]],

        [[0.7432, 0.6573, 0.8817],
         [0.7530, 0.2061, 0.4182]]])

In [28]:
d[0]

tensor([[0.0600, 0.9531, 0.0988],
        [0.6665, 0.7784, 0.6273]])

In [30]:
# dimension = 4 (CNN)
e = torch.rand(1,3,28,28)
e

tensor([[[[0.2520, 0.4810, 0.2451,  ..., 0.0994, 0.6881, 0.9702],
          [0.2229, 0.2060, 0.7425,  ..., 0.1614, 0.5968, 0.8479],
          [0.9590, 0.0623, 0.5128,  ..., 0.9248, 0.7135, 0.2632],
          ...,
          [0.9152, 0.1650, 0.9704,  ..., 0.5455, 0.9721, 0.8931],
          [0.1835, 0.4492, 0.3958,  ..., 0.9861, 0.4727, 0.8550],
          [0.2567, 0.0320, 0.4300,  ..., 0.0869, 0.0611, 0.8185]],

         [[0.0493, 0.3441, 0.8145,  ..., 0.6439, 0.0718, 0.8248],
          [0.2667, 0.6747, 0.7712,  ..., 0.7455, 0.7800, 0.0027],
          [0.6949, 0.9472, 0.7578,  ..., 0.4785, 0.3717, 0.6606],
          ...,
          [0.4910, 0.4191, 0.4789,  ..., 0.8637, 0.1667, 0.7614],
          [0.8234, 0.0494, 0.7978,  ..., 0.3380, 0.5727, 0.5733],
          [0.9642, 0.1016, 0.6309,  ..., 0.3991, 0.9832, 0.7399]],

         [[0.2412, 0.3532, 0.7427,  ..., 0.9189, 0.6189, 0.6714],
          [0.9610, 0.0397, 0.3593,  ..., 0.2348, 0.7243, 0.4607],
          [0.7380, 0.6041, 0.3965,  ..., 0

In [33]:
e.numel() # 内存

2352

In [34]:
e.dim()

4